// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDezPBrQdwLi4i0vj4lbzXlNfV69feSDL4',
    appId: '1:767885999344:web:612312f9d91ad356571635',
    messagingSenderId: '767885999344',
    projectId: 'phone-authebtication-firebase',
    authDomain: 'phone-authebtication-firebase.firebaseapp.com',
    databaseURL: 'https://phone-authebtication-firebase-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'phone-authebtication-firebase.appspot.com',
    measurementId: 'G-97BDF05N0Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuqsv8s4o1kur8XEj_erSWQ0zEaOo5-a8',
    appId: '1:767885999344:android:c8b731cb6ed80fab571635',
    messagingSenderId: '767885999344',
    projectId: 'phone-authebtication-firebase',
    databaseURL: 'https://phone-authebtication-firebase-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'phone-authebtication-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcP4dutVGXF9VPDP5veBxOqqJmECs_OPI',
    appId: '1:767885999344:ios:458cfa4a7e1408b8571635',
    messagingSenderId: '767885999344',
    projectId: 'phone-authebtication-firebase',
    databaseURL: 'https://phone-authebtication-firebase-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'phone-authebtication-firebase.appspot.com',
    androidClientId: '767885999344-3mqk1pv1m7svi6ibaetccr65cgp68ise.apps.googleusercontent.com',
    iosClientId: '767885999344-1d1agssoknshiuh0nbm6c8gri13kqg2h.apps.googleusercontent.com',
    iosBundleId: 'com.example.phoneAuthFirebase',
  );
}
